### ISSUE TITLE
ddc.get_vcp_feature()支持16进制和10进制数字输入，应用不支持。

### ISSUE THREAD

**Issue by YangtseSu** [lilydjwg/monitor-control#1]
Mesa DDCCI标准\MCCS标准，均用十六进制表示Feature code。
ddc.get_vcp_feature()支持16进制和10进制数字输入。（0x10或者16）
clap::Parser之后就不支持了。

**Comment by lilydjwg** [comment]
现在支持了，顺便多支持了一个 h 后缀。
